services:
  eureka-server:
    hostname: eureka-server
    ports:
      - "8761:8761"
    build: ./EurekaServer


  gateway-server:
    build: ./gatewayserverpb
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    links:
      - "eureka-server"


  project-db:
    build: ./project-java-micro
    links:
      - "eureka-server"
      - "my-rabbit"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      spring_rabbitmq_host: my-rabbit
      
  service-db:
    build: ./service-java-micro
    links:
      - "eureka-server"
      - "my-rabbit"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      spring_rabbitmq_host: my-rabbit
      
  comments-db:
    build: ./comments
    links:
      - "eureka-server"
      - "my-rabbit"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      spring_rabbitmq_host: my-rabbit
      
  alunos-db:
    build: ./alunoservice
    links:
      - "eureka-server"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  my-rabbit:
    image: rabbitmq:4.0.0-beta.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    environment:
      - my-rabbit_DEFAULT_USER=guest
      - my-rabbit_DEFAULT_PASS=guest
      - my-rabbit_DEFAULT_VHOST=/


